Search/create search logic
nzambonivergara/whats-cookin pull request #40
Opened 2021-09-03 02:25 UTC by PaulTimothyChambers

**What (if any) features are you implementing?**
- Search functionality

**What (if anything) did you refactor?**
- The index.html file to include script.js in the script tag

**Were there any issues that arose?**
- N/A

**Any other comments, questions, or concerns?**
- N/A

**Is there anything you need from your team?**
- N/A

2021-09-03 20:26 UTC, HartiganHM requested changes
Overall, this looks really good! Nice use of `reduce` and `filter`! I left some notes about things that can/should be changed. At a high level, I think there are some refactors you made that don't necessarily make things easier to follow, even if they technically reduce the number of lines of code.

Also, this PR is titled **Search/create search logic**, but there are updates to tests. In general, it's good to keep your PR scoped to what it's about, so to me, the tests would be considered "scope creep" (aka doing extra work outside of what's needed). This isn't necessarily a problem, but, if you do this, make sure to call it out in your PR description OR open it in a separate PR 🙂

2021-09-03 20:26 UTC, HartiganHM commented on src/classes/User.js
> +    let favRecipe = this.favoriteRecipes;
All of these `let` variables can be `const`. Using `Array.push` doesn't re-assing the variable, it just updates it, so `const` makes the most sense here.

2021-09-03 20:26 UTC, HartiganHM commented on src/classes/User.js
> +  // }
In general, if code isn't being used, you should remove it. I usually like to have a `scratchpad.js` file locally that's added to my `.gitignore` which lets me hold on to work-in-progress code and test things out without pushing it up to the actual codebase.

2021-09-03 20:26 UTC, HartiganHM commented on src/classes/User.js
> +    this.getIngredientNames( ingredientsData);
Looks like you have an extra space before `ingredientsData`.

2021-09-03 20:26 UTC, HartiganHM commented on src/data/ingredients-sample.js
> +export const ingredientsData = [
It looks like these files are in your other PR, too. Depending on which one gets merged first, just make sure you update the one that hasn't been merged.

2021-09-03 20:26 UTC, HartiganHM commented on src/index.html
> +  <script src="./scripts.js"></script>
I don't think this is needed when using webpack. Try removing it and see if the application still runs as expected with `npm run start`. I could totally be wrong though 🙂

2021-09-03 20:26 UTC, HartiganHM commented on src/scripts.js
> +// let recipesList = recipesData;  need to plug in recipeData here
Again, comments should be removed for PRs unless they're providing specific in-code context that would help other devs.

2021-09-03 20:26 UTC, HartiganHM commented on src/scripts.js
> +let mainGlide = document.querySelector('.search-ingredient-glide__images-container');
These should also be `const` unless they're reassigned somewhere. From what I can see, it doesn't look like they are.

2021-09-03 20:26 UTC, HartiganHM commented on src/scripts.js
> +searchBar.addEventListener('keyup', (e) => {
Everything here should be broken out into a separate function versus inline with the event listener.

Also, we have a rule on our team that variable names should be at least three characters long, so we never use `e` and just spell out `event`. This is more preference than anything, but, as you start to work in the field, it's helpful to have _more_ context than less.

2021-09-03 20:26 UTC, HartiganHM commented on src/scripts.js
> +  const searchTerm = e.target.value;
I would update this to use `.toLowerCase()` with the variable definitions so you don't have to use it three times below (e.g. `const searchTerm = e.target.value.toLowerCase();`).

2021-09-03 20:26 UTC, HartiganHM commented on src/scripts.js
> +    || recipe.ingredients.toString().toLowerCase().includes(searchTerm.toLowerCase());
There's _a lot_ going on in this return statement that makes it hard to read. I would suggest setting all of these to variables and then returning something easier to read. Something like:

```javascript
const recipeIncludesName = recipe.name.toLowerCase().includes(searchTerm);
...

return recipeIncludesName || ... ;
```

2021-09-03 20:26 UTC, HartiganHM commented on src/scripts.js
> +  filteredRecipes.forEach((recipe) => {
This could also be broken out into a dedicated function.

2021-09-03 20:26 UTC, HartiganHM commented on test/User-test.js
> +  let user, recipeOne, recipeTwo, recipeThree, tagOne, tagTwo, tagThree, ingredientsOne, ingredientsTwo, ingredientsThree, nameOne;
You could take this as a preference, but I wouldn't advise updating to this type of syntax. I personally find it more confusing and harder to read, plus, even though it's a "one-liner", it's a _very long_ one-liner. I've also never seen anyone use this on the job, for what it's worth.

2021-09-03 20:26 UTC, HartiganHM commented on test/User-test.js
> +  beforeEach(function() {
No need for this change, the arrow function should work fine.

2021-09-03 20:26 UTC, HartiganHM commented on test/User-test.js
> +    nameOne = 'cookies'
Just for clarity on how `beforeEach` works, it allows you to "reset" things before each test. This is useful for things that hold onto "state" like classes, which is why `beforeEach` is awesome for stuff like `user, recipeOne, recipeTwo, etc.`. However, `tagOne, tageTwo, nameOne, etc.` never change. So, you couldn't technically make these `const` outside of the `beforeEach` or even outside of the `describe` block.

No real need to change, but food for thought.

2021-09-03 20:26 UTC, HartiganHM commented on test/User-test.js
> +    // ingredientsThree = recipeThree.getIngredientsInformation()
Again, if it isn't being used, let's remove it 🙂

2021-09-03 20:26 UTC, HartiganHM commented on test/User-test.js
> +  it.skip('should be able to filter favorites by name', function() {
Did you mean to leave these `skip` statements here?

2021-09-04 19:45 UTC, closed without merging

2021-09-04 19:46 UTC, PaulTimothyChambers commented
My mess